use std::sync::Mutex;
use rusqlite::{params,Connection};
use serde::{Deserialize,Serialize};
use tauri::State;
use uuid::Uuid;
use crate::{attachments::{ensure_learner,invalid,is_head},auth::SessionManager,commands::lock_db,error::{AppError,AppResult}};
#[derive(Debug,Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct ResourceIssue {pub id:String,pub learner_id:String,pub resource_name:String,pub issued_quantity:i64,pub returned_quantity:i64,pub issued_on:String}
#[derive(Debug,Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct SupportPlan {pub id:String,pub learner_id:String,pub goal:String,pub evidence:String,pub follow_up_on:String}
#[derive(Debug,Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct SupportSession {pub id:String,pub session_on:String,pub observation:String,pub next_step:String}
fn text(value:&str,max:usize)->AppResult<&str>{let value=value.trim();if value.is_empty()||value.len()>max{Err(invalid("Complete the required text within its length limit."))}else{Ok(value)}}
pub(crate) fn date(value: &str) -> AppResult<&str> {
 let b=value.as_bytes();
 if b.len()!=10 || b[4]!=b'-' || b[7]!=b'-' || b.iter().enumerate().any(|(i,v)| i!=4 && i!=7 && !v.is_ascii_digit()) {return Err(invalid("Choose a valid calendar date."));}
 let year=value[..4].parse::<u32>().unwrap_or(0); let month=value[5..7].parse::<u32>().unwrap_or(0); let day=value[8..].parse::<u32>().unwrap_or(0);
 let leap=year.is_multiple_of(4) && (!year.is_multiple_of(100) || year.is_multiple_of(400));
 let max=match month {1|3|5|7|8|10|12=>31,4|6|9|11=>30,2=>if leap {29}else{28},_=>0};
 if year==0 || day==0 || day>max {Err(invalid("Choose a valid calendar date."))}else{Ok(value)}
}
#[tauri::command]
pub fn issue_learning_resource(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>,learner_id:String,resource_name:String,quantity:i64,issued_on:String)->AppResult<String>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;ensure_learner(&c,&s,&a,&learner_id)?;if !(1..=1000).contains(&quantity){return Err(invalid("Quantity must be between 1 and 1000."));}let id=Uuid::now_v7().to_string();c.execute("INSERT INTO resource_issues(id,school_id,owner_user_id,learner_id,resource_name,issued_quantity,issued_on) VALUES(?1,?2,?3,?4,?5,?6,?7)",params![id,s,a,learner_id,text(&resource_name,200)?,quantity,date(&issued_on)?])?;Ok(id)}
#[tauri::command]
pub fn list_resource_issues(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>)->AppResult<Vec<ResourceIssue>>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;let head=is_head(&c,&s,&a)?;let mut stmt=c.prepare("SELECT i.id,i.learner_id,i.resource_name,i.issued_quantity,COALESCE((SELECT SUM(quantity) FROM resource_returns r WHERE r.issue_id=i.id),0),i.issued_on FROM resource_issues i WHERE school_id=?1 AND (owner_user_id=?2 OR ?3) ORDER BY i.created_at DESC")?;let rows=stmt.query_map(params![s,a,head],|r|Ok(ResourceIssue{id:r.get(0)?,learner_id:r.get(1)?,resource_name:r.get(2)?,issued_quantity:r.get(3)?,returned_quantity:r.get(4)?,issued_on:r.get(5)?}))?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}
pub fn record_return(c:&Connection,school:&str,actor:&str,id:&str,quantity:i64,reason:&str,returned_on:&str)->AppResult<String>{let head=is_head(c,school,actor)?;let mut stmt=c.prepare("SELECT learner_id,issued_on FROM resource_issues WHERE id=?1 AND school_id=?2 AND (owner_user_id=?3 OR ?4)")?;let mut rows=stmt.query(params![id,school,actor,head])?;let row=rows.next()?.ok_or(AppError::Unauthorized)?;let learner:String=row.get(0)?;let issued:String=row.get(1)?;ensure_learner(c,school,actor,&learner)?;date(returned_on)?;if returned_on<issued.as_str()||quantity<=0{return Err(invalid("Return date and quantity must match the issue."));}let rid=Uuid::now_v7().to_string();c.execute("INSERT INTO resource_returns(id,issue_id,quantity,reason,actor_user_id,returned_on) VALUES(?1,?2,?3,?4,?5,?6)",params![rid,id,quantity,text(reason,1000)?,actor,returned_on])?;Ok(rid)}
#[tauri::command]
pub fn return_learning_resource(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>,issue_id:String,quantity:i64,reason:String,returned_on:String)->AppResult<String>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;record_return(&c,&s,&a,&issue_id,quantity,&reason,&returned_on)}
#[tauri::command]
pub fn create_support_plan(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>,learner_id:String,goal:String,evidence:String,follow_up_on:String)->AppResult<String>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;ensure_learner(&c,&s,&a,&learner_id)?;let id=Uuid::now_v7().to_string();c.execute("INSERT INTO learning_support_plans(id,school_id,owner_user_id,learner_id,goal,evidence,follow_up_on) VALUES(?1,?2,?3,?4,?5,?6,?7)",params![id,s,a,learner_id,text(&goal,2000)?,text(&evidence,4000)?,date(&follow_up_on)?])?;Ok(id)}
#[tauri::command]
pub fn list_support_plans(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>)->AppResult<Vec<SupportPlan>>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;let head=is_head(&c,&s,&a)?;let mut stmt=c.prepare("SELECT id,learner_id,goal,evidence,follow_up_on FROM learning_support_plans WHERE school_id=?1 AND (owner_user_id=?2 OR ?3) ORDER BY created_at DESC")?;let rows=stmt.query_map(params![s,a,head],|r|Ok(SupportPlan{id:r.get(0)?,learner_id:r.get(1)?,goal:r.get(2)?,evidence:r.get(3)?,follow_up_on:r.get(4)?}))?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}
#[tauri::command]
pub fn record_support_session(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>,plan_id:String,session_on:String,observation:String,next_step:String)->AppResult<String>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;let head=is_head(&c,&s,&a)?;let learner:String=c.query_row("SELECT learner_id FROM learning_support_plans WHERE id=?1 AND school_id=?2 AND (owner_user_id=?3 OR ?4)",params![plan_id,s,a,head],|r|r.get(0))?;ensure_learner(&c,&s,&a,&learner)?;let id=Uuid::now_v7().to_string();c.execute("INSERT INTO learning_support_sessions(id,plan_id,actor_user_id,session_on,observation,next_step) VALUES(?1,?2,?3,?4,?5,?6)",params![id,plan_id,a,date(&session_on)?,text(&observation,4000)?,text(&next_step,2000)?])?;Ok(id)}
#[tauri::command]
pub fn list_support_sessions(db:State<'_,Mutex<Connection>>,sessions:State<'_,SessionManager>,plan_id:String)->AppResult<Vec<SupportSession>>{let c=lock_db(&db);let(a,s)=sessions.require_active_session(&c)?;let head=is_head(&c,&s,&a)?;let allowed:bool=c.query_row("SELECT EXISTS(SELECT 1 FROM learning_support_plans WHERE id=?1 AND school_id=?2 AND (owner_user_id=?3 OR ?4))",params![plan_id,s,a,head],|r|r.get(0))?;if !allowed{return Err(AppError::Unauthorized);}let mut stmt=c.prepare("SELECT id,session_on,observation,next_step FROM learning_support_sessions WHERE plan_id=?1 ORDER BY created_at DESC")?;let rows=stmt.query_map([plan_id],|r|Ok(SupportSession{id:r.get(0)?,session_on:r.get(1)?,observation:r.get(2)?,next_step:r.get(3)?}))?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}
#[cfg(test)]mod tests{use super::*;#[test]fn rejects_invalid_calendar_dates(){assert!(date("2026-02-30").is_err());assert!(date("2026-02-28").is_ok());assert!(date("2024-02-29").is_ok());assert!(date("2100-02-29").is_err());assert!(date("0000-01-01").is_err());assert!(date("2026-1-01").is_err());}#[test]fn prevents_over_return_at_database_boundary(){let c=Connection::open_in_memory().unwrap();c.execute_batch("CREATE TABLE schools(id TEXT PRIMARY KEY);CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE learners(id TEXT PRIMARY KEY);").unwrap();c.execute_batch(include_str!("db/sql/0047_resource_issues.sql")).unwrap();c.execute("INSERT INTO resource_issues(id,school_id,owner_user_id,learner_id,resource_name,issued_quantity,issued_on) VALUES ('i','s','u','l','Book',2,'2026-10-04')",[]).unwrap();c.execute("INSERT INTO resource_returns(id,issue_id,quantity,reason,actor_user_id,returned_on) VALUES ('a','i',1,'Good','u','2026-10-05')",[]).unwrap();assert!(c.execute("INSERT INTO resource_returns(id,issue_id,quantity,reason,actor_user_id,returned_on) VALUES ('b','i',2,'Good','u','2026-10-05')",[]).is_err());}}
